[program:laravel-reverb]
process_name=%(program_name)s
command=/usr/bin/php /home2/webadminpruebas/web/artisan reverb:start --host=0.0.0.0 --port=8080
autostart=true
autorestart=true
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/laravel-reverb.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=10
environment=LARAVEL_ENV=production
user=www-data
startsecs=10
stopwaitsecs=10
priority=999
