[program:laravel-queue-worker]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /home2/webadminpruebas/web/artisan queue:work --queue=default,emails,notifications --timeout=0 --tries=3 --sleep=3
autostart=true
autorestart=true
numprocs=4
redirect_stderr=true
stdout_logfile=/var/log/supervisor/laravel-queue-worker.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=10
environment=LARAVEL_ENV=production
user=www-data
startsecs=10
stopwaitsecs=10
priority=999
