[program:laravel-health-worker]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /home/webadmin/web/artisan queue:work database --queue=health --sleep=3 --tries=3 --max-time=300 --timeout=300
autostart=true
autorestart=true
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/laravel-health-worker.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=10
environment=LARAVEL_ENV=production
user=www-data
startsecs=10
stopwaitsecs=10
priority=999
