<?php

return [
    App\Providers\AppServiceProvider::class,
    Modules\Media\Providers\MediaServiceProvider::class,
    Modules\Theme\Providers\ThemeServiceProvider::class,
    Modules\Activity\Providers\ActivityServiceProvider::class,
    Modules\Auth\Providers\AuthServiceProvider::class,
    Modules\Backup\Providers\BackupServiceProvider::class,
    Modules\Core\Providers\CoreServiceProvider::class,
    Modules\Database\Providers\DatabaseServiceProvider::class,
    Modules\Document\Providers\DocumentsServiceProvider::class,
    Modules\Event\Providers\EventServiceProvider::class,
    Modules\Health\Providers\HealthServiceProvider::class,
    Modules\Horizon\Providers\HorizonServiceProvider::class,
    Modules\Mailer\Providers\MailerServiceProvider::class,
    Modules\MailsSettings\Providers\MailsSettingsServiceProvider::class,
    Modules\Modules\Providers\EventServiceProvider::class,
    Modules\Notification\Providers\NotificationServiceProvider::class,
    Modules\Prestashop\Providers\PrestashopServiceProvider::class,
    Modules\Pulse\Providers\EventServiceProvider::class,
    Modules\Role\Providers\RoleServiceProvider::class,
    Modules\Storage\Providers\StorageServiceProvider::class,
    Modules\System\Providers\SystemServiceProvider::class,
    Modules\User\Providers\UserServiceProvider::class,
    Modules\Warehouse\Providers\WarehouseServiceProvider::class,
    Modules\Webhook\Providers\WebhookServiceProvider::class,
    // Modules\Telescope\Providers\TelescopeServiceProvider::class,
];
