
<div class="page-content">
    <div class="container">
        <section id="content" class="page-content page-cms cms-pages page-cms-{$cms.id}">

            <div class="exchangesandreturns">


            <div class="col-sp-12 col-xs-12 col-sm-12 col-md-12 col-lg-12">

                <div id="category-description" class="exchangesandreturns-description">

                    <h3><span><strong>{l s='EXCHANGE AND RETURN POLICY exchangesandreturns' mod='alsernetcontents'} </strong></span></h3>
                    <p>{l s='All the inventaries we sell are from top-quality manufacturers. They offer the highest quality and the best guarantee. However, if for any reason you do not agree with the purchase, you may choose to exchange, return or withdraw. To do so, you have a period of fifteen (15) calendar days from the time of receipt. exchangesandreturns' mod='alsernetcontents'} </p>
                    <p>{l s='To make such a return, the product must be in perfect condition and in its original packaging. exchangesandreturns' mod='alsernetcontents'} </p>
                    <p>{l s='In the event that the return is made for reasons not attributable to Álvarez, the Buyer will be responsible for the costs generated by this return. In any case, the return of defective inventaries and incorrect shipments will be accepted, with Álvarez being responsible for the shipping costs provided that the customer communicates this circumstance at the time of receiving the order. exchangesandreturns' mod='alsernetcontents'} </p>
                    <p>{l s='In any case, the return of defective inventaries and erroneous shipments will be admitted, being Álvarez who will be responsible for the shipping costs provided that the customer communicates this circumstance at the time of receipt of the order.' mod='alsernetcontents'} </p>
                    {if $iso == 'es'}
                    <p>{l s='Exceptionally, for clothing and footwear items purchased at www.a-alvarez.com, free returns are accepted. This is a one-off promotion, only for mainland Spain and applicable only to inventaries marked with free returns (you will see a banner/ad on the product itself). The conditions for returns will be the same as for any other product: exchangesandreturns' mod='alsernetcontents'} </p>

                    <ul>
                        <li>
                            <p>{l s='Maximum period of fifteen (15) calendar days from the time of receipt. exchangesandreturns' mod='alsernetcontents'} </p>
                        </li>
                        <li>
                            <p>{l s='The product must be in perfect condition and in its original packaging. exchangesandreturns' mod='alsernetcontents'} </p>
                        </li>
                    </ul>
                    {/if}

                    <p>{l s='Return of orders must be sent to the address of Álvarez, Polígono de Pocomaco, Primera Avenida, 81. Parcela C-13, 15190 Mesoiro, La Coruña. Once the buyer has exercised the right of withdrawal and once the merchandise has been received in our warehouses and its condition has been verified, Álvarez will act in the manner indicated by the buyer: refund of the amount or exchange of the merchandise. exchangesandreturns' mod='alsernetcontents'} </p>
                    <p>{l s='Videos, discs, video games or other inventaries susceptible to immediate copying may only be exchanged for another identical title. exchangesandreturns' mod='alsernetcontents'} </p>
                    <p>{l s='Electronic inventaries may only be returned if they have not been opened. For the return they must be perfectly sealed and not have been manipulated in any way. exchangesandreturns' mod='alsernetcontents'} </p>

                    <p>{l s='No changes or returns are allowed on the following inventaries: exchangesandreturns' mod='alsernetcontents'} </p>
                    <ul>
                        <li>
                            <p>{l s='Weapons exchangesandreturns' mod='alsernetcontents'} </p>
                        </li>
                        <li>
                            <p>{l s='Gun cabinets exchangesandreturns' mod='alsernetcontents'} </p>
                        </li>
                        <li>
                            <p>{l s='Products requested exclusively for the client or that have required some customization exchangesandreturns' mod='alsernetcontents'} </p>
                        </li>
                        <li>
                            <p>{l s='Veterinary medicines exchangesandreturns' mod='alsernetcontents'} </p>
                        </li>
                        <li>
                            <p>{l s='Hygienic masks exchangesandreturns' mod='alsernetcontents'} </p>
                        </li>
                    </ul>

                    <p><b>{l s='SPECIAL PROMOTION TERMS – “EXTENDED RETURN PERIOD” CHRISTMAS 2025-2026' mod='alsernetcontents'}</b></p>

                    {assign var="exchangeandreturnstext" value={l s='Exchange conditions' mod='alsernetcontents'}}
                    <p>{$exchangeandreturnstext|replace:" || ":"<br>" nofilter}</p>


                </div>
            </div>
        </section>
    </div>
</div>
