<?php
/**
 * Page Cache Ultimate, Page Cache standard and Speed pack are powered by Jpresta (jpresta . com)
 *
 * @author    Jpresta
 * @copyright Jpresta
 * @license   See the license of this module in file LICENSE.txt, thank you.
 */

if (!defined('_PS_VERSION_')) {
    exit;
}

/**
 * Implements getJprestaModelObjectClassName() and getJprestaModelObjectId() to enable the HTML cache provided by the
 * module Page Cache Ultimate created by jpresta.com
 */
class af_producttagsprotagsModuleFrontControllerOverride extends af_producttagsprotagsModuleFrontController
{
    /**
     * @return string The ObjectModel class name to be used by Page Cache Ultimate module to refresh the cache of pages generated by this controller
     */
    public static function getJprestaModelObjectClassName()
    {
        // A fake class to enable the cache
        return 'AdvancedTagsModel';
    }

    /**
     * @return int|null The ID of the current ObjectModel (if any) to be used by Page Cache Ultimate module to refresh the cache of pages generated by this controller
     */
    public function getJprestaModelObjectId()
    {
        $tag = AdvancedTagsModel::getTagByLinkRewrite(Tools::getValue('tagName'), $this->context->language->id);
        if (empty($tag)) {
            $tag_name = str_replace('-', ' ', Tools::getValue('tagName'));
            $tag_id = AdvancedTagsModel::getIdTagByName($tag_name, $this->context->language->id);
        } else {
            $tag_id = $tag['adtag_id_tag'];
        }
        if (!$tag_id) {
            $tag_id = null;
        }
        return $tag_id;
    }

    /**
     * List all URLs generated by this controller for the current shop context and the specified language.
     * This is used by the Jresta-Cache-Warmer service to generate the cache of these pages.
     * @param $id_lang int ID of the language
     * @return string[] All URLs to warmup
     */
    public static function getJprestaAllURLs($id_lang) {
        $context = Context::getContext();
        $links = [];
        $afsp = Module::getInstanceByName('af_producttagspro');
        if ($afsp) {
            if (Group::isFeatureActive()) {
                $groups = FrontController::getCurrentCustomerGroups();

                $tags = JPresta\SpeedPack\JprestaUtils::dbSelectRows('
                    SELECT t.name, adTag.`adtag_link_rewrite`
                    FROM `' . _DB_PREFIX_ . 'tag_count` pt
                    LEFT JOIN `' . _DB_PREFIX_ . 'tag` t ON (t.id_tag = pt.id_tag)
                    LEFT JOIN `' . _DB_PREFIX_ . 'af_advanced_tags` adTag ON (adTag.adtag_id_tag = t.id_tag)
                    WHERE (adTag.`adtag_is_show` = 1 OR adTag.`adtag_is_show` IS NULL) AND pt.`id_group` ' . (count($groups) ? 'IN (' . implode(',', $groups) . ')' : '= 1') . '
                    AND pt.`id_lang` = ' . (int) $id_lang . ' AND pt.`id_shop` = ' . (int) $context->shop->id);
            } else {
                $tags = JPresta\SpeedPack\JprestaUtils::dbSelectRows('
                    SELECT t.name
                    FROM `' . _DB_PREFIX_ . 'tag_count` pt
                    LEFT JOIN `' . _DB_PREFIX_ . 'tag` t ON (t.id_tag = pt.id_tag)
                    LEFT JOIN `' . _DB_PREFIX_ . 'af_advanced_tags` adTag ON (adTag.adtag_id_tag = t.id_tag)
                    WHERE (adTag.`adtag_is_show` = 1 OR adTag.`adtag_is_show` IS NULL) AND pt.id_group = 0 AND pt.`id_lang` = ' . (int) $id_lang . ' AND pt.`id_shop` = ' . (int) $context->shop->id);
            }
            foreach ($tags as $tag) {
                $links[] = $afsp->getUrlFrontTag($tag['name'], isset($tag['adtag_link_rewrite']) ? $tag['adtag_link_rewrite'] : null, $id_lang);
            }
        }
        return $links;
    }

    /**
     * An estimated number of URLs that will be returned by self::getJprestaAllURLs() for the current shop context.
     * Since we don't have the id_lang parameter we recommend to return the number of URLs for the language that have
     * the most URLs.
     * @return int The estimated number of URLs to warmup for the current shop context
     */
    public static function getJprestaAllURLsCount() {
        $queryCountPages = '
                    SELECT COUNT(*)
                    FROM `' . _DB_PREFIX_ . 'tag_count` pt
                    LEFT JOIN `' . _DB_PREFIX_ . 'tag` t ON (t.id_tag = pt.id_tag)
                    LEFT JOIN `' . _DB_PREFIX_ . 'af_advanced_tags` adTag ON (adTag.adtag_id_tag = t.id_tag)
                    WHERE (adTag.`adtag_is_show` = 1 OR adTag.`adtag_is_show` IS NULL) AND pt.id_group = '.(Group::isFeatureActive() ? 1 : 0).' AND pt.`id_lang` = ' . (int) Configuration::get('PS_LANG_DEFAULT') . ' AND pt.`id_shop` = ' . (int) Shop::getContextShopID();
        return (int) JPresta\SpeedPack\JprestaUtils::dbGetValue($queryCountPages);
    }
}
